version: "3.3"

# YugabyteDB 3-node local cluster for development
# Reference: https://docs.yugabyte.com/preview/quick-start/docker/

services:
  yb-node-1:
    image: yugabytedb/yugabyte:2.25.2.0-b359
    container_name: yb-node-1
    hostname: yb-node-1
    command: [
      "bash", "-lc",
      "bin/yugabyted start \
        --background=false \
        --base_dir=/home/yugabyte/yb_data \
        --advertise_address=yb-node-1 \
        --master_flags=use_node_to_node_encryption=false \
        --tserver_flags=use_node_to_node_encryption=false"
    ]
    volumes:
      - yb-node-1-data:/home/yugabyte/yb_data
    ports:
      - "7000:7000"   # master web ui
      - "9000:9000"   # tserver web ui
      - "15433:15433" # ysql web ui
      - "5433:5433"   # ysql
      - "9042:9042"   # ycql
    networks:
      - yb-net
    healthcheck:
      test: ["CMD", "bash", "-lc", "bin/yugabyted status --base_dir=/home/yugabyte/yb_data | grep -q 'Status *: Running'" ]
      interval: 10s
      timeout: 5s
      retries: 12
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576

  yb-node-2:
    image: yugabytedb/yugabyte:2.25.2.0-b359
    container_name: yb-node-2
    hostname: yb-node-2
    command: [
      "bash", "-lc",
      "bin/yugabyted start \
        --background=false \
        --base_dir=/home/yugabyte/yb_data \
        --advertise_address=yb-node-2 \
        --join=yb-node-1 \
        --master_flags=use_node_to_node_encryption=false \
        --tserver_flags=use_node_to_node_encryption=false"
    ]
    volumes:
      - yb-node-2-data:/home/yugabyte/yb_data
    depends_on:
      - yb-node-1
    restart: on-failure
    command: [
      "bash", "-lc",
      "for i in {1..60}; do (echo > /dev/tcp/yb-node-1/15433) >/dev/null 2>&1 && break; echo 'waiting for yb-node-1:15433'; sleep 2; done; \ 
       bin/yugabyted start \
        --background=false \
        --base_dir=/home/yugabyte/yb_data \
        --advertise_address=yb-node-2 \
        --join=yb-node-1 \
        --master_flags=use_node_to_node_encryption=false \
        --tserver_flags=use_node_to_node_encryption=false"
    ]
    networks:
      - yb-net
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576

  yb-node-3:
    image: yugabytedb/yugabyte:2.25.2.0-b359
    container_name: yb-node-3
    hostname: yb-node-3
    command: [
      "bash", "-lc",
      "bin/yugabyted start \
        --background=false \
        --base_dir=/home/yugabyte/yb_data \
        --advertise_address=yb-node-3 \
        --join=yb-node-1 \
        --master_flags=use_node_to_node_encryption=false \
        --tserver_flags=use_node_to_node_encryption=false"
    ]
    volumes:
      - yb-node-3-data:/home/yugabyte/yb_data
    depends_on:
      - yb-node-1
    restart: on-failure
    command: [
      "bash", "-lc",
      "for i in {1..60}; do (echo > /dev/tcp/yb-node-1/15433) >/dev/null 2>&1 && break; echo 'waiting for yb-node-1:15433'; sleep 2; done; \ 
       bin/yugabyted start \
        --background=false \
        --base_dir=/home/yugabyte/yb_data \
        --advertise_address=yb-node-3 \
        --join=yb-node-1 \
        --master_flags=use_node_to_node_encryption=false \
        --tserver_flags=use_node_to_node_encryption=false"
    ]
    networks:
      - yb-net
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576

networks:
  yb-net:
    driver: bridge

volumes:
  yb-node-1-data:
  yb-node-2-data:
  yb-node-3-data:
  